scope: postgres_cluster
namespace: /service/
name: patroni2

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni2:8008 

etcd:
  hosts: "etcd1:2379,etcd2:2379,etcd3:2379"

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        shared_buffers: 1GB
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni2:5432  
  data_dir: /var/lib/postgresql/data/pgdata
  bin_dir: /usr/lib/postgresql/13/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: replicatorpass
    superuser:
      username: postgres
      password: postgrespass
  parameters:
    unix_socket_directories: '/var/run/postgresql'