version: '3.8'

services:
  # ETCD Cluster (3 nodes for high availability)
  etcd1:
    image: quay.io/coreos/etcd:v3.4.14
    container_name: etcd1
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
    networks:
      - cluster_net
    ports:
      - "2379:2379"  # Client port for etcd1
      - "2380:2380"  # Peer port for etcd1

  etcd2:
    image: quay.io/coreos/etcd:v3.4.14
    container_name: etcd2
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
    networks:
      - cluster_net
    ports:
      - "2479:2379"  # Client port for etcd2
      - "2480:2380"  # Peer port for etcd2

  etcd3:
    image: quay.io/coreos/etcd:v3.4.14
    container_name: etcd3
    environment:
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
    networks:
      - cluster_net
    ports:
      - "2579:2379"  # Client port for etcd3
      - "2580:2380"  # Peer port for etcd3

  # Patroni/PostgreSQL Nodes
  patroni1:
    image: ghcr.io/zalando/spilo-15:2.1-p7
    container_name: patroni1
    environment:
      - PATRONI_NAME=patroni1
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni1:8008
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni1:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data/pgdata
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicatorpass
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_admin_PASSWORD=adminpass
      - PATRONI_ETCD_URL=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
    volumes:
      - patroni1_data:/var/lib/postgresql/data
      - ./patroni1.yml:/etc/patroni.yml
    networks:
      - cluster_net
    ports:
      - "8008:8008"  # Patroni REST API
      - "5433:5432"  # PostgreSQL (mapped to different port to avoid conflict)

  patroni2:
    image: ghcr.io/zalando/spilo-15:2.1-p7
    container_name: patroni2
    environment:
      - PATRONI_NAME=patroni2
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni2:8008
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni2:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data/pgdata
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicatorpass
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_admin_PASSWORD=adminpass
      - PATRONI_ETCD_URL=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
    volumes:
      - patroni2_data:/var/lib/postgresql/data
      - ./patroni2.yml:/etc/patroni.yml
    networks:
      - cluster_net
    ports:
      - "8009:8008"  # Patroni REST API
      - "5434:5432"  # PostgreSQL (mapped to different port to avoid conflict)

  # HAProxy for load balancing and failover
  haproxy:
    image: haproxy:2.4
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5432:5432"  # PostgreSQL primary endpoint
      - "7000:7000"  # HAProxy stats dashboard
    networks:
      - cluster_net
    depends_on:
      - patroni1
      - patroni2

networks:
  cluster_net:
    driver: bridge

volumes:
  patroni1_data:
  patroni2_data: